create or replace trigger sup_exem
    AFTER DELETE ON EXEMPLAIREEMPRUNTE
BEGIN
    DELETE FROM Emprunt WHERE (Emprunt.NUMA, Emprunt.DATEE) NOT IN
        (SELECT EXEMPLAIREEMPRUNTE.NUMA, EXEMPLAIREEMPRUNTE.DATEE FROM EXEMPLAIREEMPRUNTE);
END;